---
- name: Install WordPress step-by-step
  hosts: all
  vars:
    db_user: s
    db_password: s
    db_name: s
  become: true
  tasks:
    - name: Install Apache in Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: Start Apache in Ubuntu
      service:
        name: apache2
        state: started
      become: true

    - name: Remove index.html and replace with info.php
      command: >
        rm -f /var/www/html/index.html &&
        echo "<?php phpinfo(); ?>" > /var/www/html/info.php

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
      become: true

    - name: Start MySQL in Ubuntu
      service:
        name: mysql
        state: started
      become: true

    - name: Install PHP and required modules
      apt:
        name:
          - libapache2-mod-php
          - php
          - php-mysql
          - phpmyadmin
          - php-mbstring
          - php-zip
          - php-gd
          - php-json
          - php-curl
          - php-xml
          - php-mysqli
        state: present
      become: true

    - name: Restart Apache in Ubuntu
      service:
        name: apache2
        state: restarted
      become: true

    - name: Install Python MySQLdb module
      apt:
        name: python3-mysqldb
        state: present
      become: true

    - name: Create MySQL database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_host: localhost
        login_user: root
        login_password: ""

    - name: Create MySQL user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        host: localhost
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_host: localhost
        login_user: root
        login_password: ""

    - name: Download and extract WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress archive
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set ownership of WordPress files
      file:
        path: /var/www/html/
        state: directory
        owner: www-data
        group: www-data
        recurse: yes
      become: true

    - name: Set permissions of WordPress files
      file:
        path: /var/www/html/
        state: directory
        mode: '0755'
        recurse: yes
